### PR TITLE
Change project structure

### PR DESCRIPTION
**Pull request by hannesa2**
It's about to open project with any Intellij IDE (Android Studio) and see complete project.
Additionally, CI yaml files can be edited in Android Studio now

### CODE REVIEW

**Comment by hannesa2** [comment]
@topherbuckley 
Here are your doubt: 

> I'd be against this for [these](https://github.com/ytai/ioio/commit/af08e734e2a7693c61c394ef17fd571550b41b75#commitcomment-42003878) reasons.

**Comment by hannesa2** [comment]
> I'd vote against that as the ioio project is more than just a software project, and the development of the hardware and firmware are completely isolated from the software as far as I know, so keeping them structurally like that makes the most sense to me. 

The complete repo is a software project !
I don't changed the non-Andorid/PC stuff like, hardware, firmware

> Especially if it is just to avoid a single line in yaml

It's more then this. It's about
* to see **all** project related stuff in IDE. Workflow, firmeware, software, hardware....
* make Espresso tests work properly
* get rid of symlinks and develop pipeline in IDE

**Comment by hannesa2** [comment]
I only see benefits and no disadvantages

**Comment by hannesa2** [comment]
Without any strong reason against it (which I don't see), I will merge it.

**Comment by topherbuckley** [comment]
You're in control, but I'll still give my dissent. 

> The complete repo is a software project !

I disagree. The most obvious example being the hardware directory being called that for a reason. The IOIO board is a hardware and software project. The hardware folder contains all you'd need to reproduce the physical board, and these files can be updated and tracked with git as well. I have several revisions of the board here in our lab that can be traced directly to versions here.  

For us, who are familiar with the change, it is not so confusing, but put yourself into the shoes of someone who just stumbles onto the library for the first time. I think this change makes the learning curve for anyone wanting to contribute much higher. As it stood before, there was clear separation between the fundamentally different development processes:

1. Android Java code to run on a smartphone (software)
2. C code to run on the IOIO board (firmware)
3. PCB Schematic design for creating the hardware (hardware)
4. Windows driver to run on a Windows PC (driver)
5. Bundles for releases (releases)... though this is outdated by jitpack and github releases now.
6. Bash files to run on Linux for compiling the various things in the above directories (tools)

The development, build, and use of each of these was fundamentally different from one another. As you have it organized now, there is no clear separation between these clearly defined development workflows. Now IOIODude stands on the same level as hardware, despite it being under the same gradle development process as IOIOBridge, and IOIO*. 

Additionally, the build process for everything but the Android Java code is governed by things other than gradle from what I can tell (make, cmake, bash scripts, etc.). I see no reason to give gradle access to ALL of these unrelated files. In the worst case, I could image the github actions script, or something in gradle unintentionally changing or removing something from one of these unrelated build process directories (e.g. hardware, tools, etc.). This could potentially break the build/workflow for these separate development processes, and as neither of us appear to be actively working on these other directories, this could go unnoticed for a LONG time. If and when someone went to go update these other directories, they'd have to go back in the commit history to manually find what broke everything. This doesn't seem like good development practice to me. 

A side question: I'm still not understanding the drive to do this other than a workaround for an issue with github actions, as well as you want to see the whole project in Android Studio. Why do you need to see hardware, drivers, tools, etc in Android Studio? I provided an easy way to see the workflows via a soft link, is this not sufficient for some reason?

**Pull request merged**
