### PR TITLE
Espresso test

### PR DESCRIPTION
**Pull request by hannesa2**
This is an attempt to run Espresso tests.
Most CI development can only be tested on CI, that's why development was made here https://github.com/hannesa2/ioio/pull/4 to avoid a lot of noise here.

### CODE REVIEW

**Comment by hannesa2** [comment]
I was not able to let CI tests run on a subdirectory

          cmd: cd software && ./gradlew cAT

image

I tried several ways 

      - name: Set project dir environment var
        run: echo ::set-env name=PROJECT_DIR::"$GITHUB_WORKSPACE/software" 

or this doesn't work with `uses:`

      working-directory: ./software # doesn't work with uses:

**Comment by hannesa2** [comment]
It looks like, there is a bug somewhere in Github action, which prevent of running it.

**Comment by hannesa2** [comment]
With #190 and #189 this is no more necessary.

**Comment by topherbuckley** [comment]
Sorry I've been MIA the past few days. Other projects had deadlines. I'll have a look at this tomorrow. I find it hard to believe a runner cannot do something to a specific directory and only to root, but maybe I'll come to the same conclusion.

**Comment by hannesa2** [comment]
> I find it hard to believe a runner cannot do something to a specific directory and only to root, but maybe I'll come to the same conclusion.

If you find a solution: go ahead. 
I spent too much time on it, that's why I go with the pragmatic solution and change the project structure

**Pull request closed without merging**
