### PR TITLE
Add connection identifier to logging. 

### PR DESCRIPTION
**Pull request by freemansoft**
Add a connection identifier() method to IOIOConnection that can be used for logging.  Update connection setup logging to use identifier

Change TAG generation to use class.getShortName() instead of hard coded string.
This more follows log4j standard usage for class level loggers.

modify .gitignore filter .settings from checkins in the software tree

### CODE REVIEW

**Comment by freemansoft** [comment]
There two commits that should make up this pull requests.  I found 3 projects that had classes in them that implement the same interface and needed to implement the same new identifier() method. https://github.com/freemansoft/ioio/commit/ef1979f0bc50c21a5a34a301ac1c6b0009d947a7 and https://github.com/freemansoft/ioio/commit/84623505bc075cd171f4fc1842581cf82cd0410d

**Comment by ytai** [comment]
Thanks for doing this! Added some comments to both commits. Would be happy to merge if those get resolved.

**Comment by vivekaris** [comment]
Sir  is anyway to change default pairing pin 4545.

**Comment by ytai** [comment]
This is totally the wrong place to ask this question and if you search the
ioio-users forum you'll find that this question has been asked and answered
(and the answer is yes).

**Comment by freemansoft** [comment]
I've made the suggested changes.  This makes some of the identifiers a little longer.  "COM5" becomes SerialPortIOIOConnection(COM5)

**Comment by freemansoft** [comment]
Are you interested in pulling this?

**Pull request closed without merging**
