### PR TITLE
Adding AppCompat theme to all Android Manifests.

### PR DESCRIPTION
**Pull request by topherbuckley**
Otherwise all android apps will crash due to their dependency on IOIOActivity which inherits from AppCompatActivity

### CODE REVIEW

**Comment by hannesa2** [comment]
The CI doesn't run because it only run when you want to merge to `master`. Maybe I should change it.

Anyway, I run into errors with this

`~/ioio/software/applications/HelloIOIO/src/main/AndroidManifest.xml:8:5-40:19: AAPT: error: resource style/Theme.AppCompat (aka ioio.examples.hello:style/Theme.AppCompat) not found.`

**Comment by hannesa2** [comment]
I made #176 reduced to only your commit and as target branch `master` to let CI run. There you see the findings from CI

**Review by hannesa2 — CHANGES_REQUESTED** [review]
It needs more work, please see #176 

I thinking about to revert 7397a935f41b09 "Changed inheritance from Activity to AppCompatActivity"
and we do this in a new pull request again, but before I add Espresso test, to see, if it works

**Comment by topherbuckley** [comment]
>Anyway, I run into errors with this

>~/ioio/software/applications/HelloIOIO/src/main/AndroidManifest.xml:8:5-40:19: AAPT: error: resource style/Theme.AppCompat (aka ioio.examples.hello:style/Theme.AppCompat) not found.

Sorry, not sure why I didn't catch this prior to the pull request. I know this error, and the fix. I'm working on this now. I'll go ahead and make the necessary commits to ytai/theme and recreate a new pull request from there to master.

**Pull request closed without merging**
