### PR TITLE
Test jitpack.io usage

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by topherbuckley** [comment]
Built successfully. Tested on Nexus 5 and crashed due to AppCompat theme missing in manifests. Updated this and works with a IOIOBoard to light the yellow LED. Will update all manifests to include this.

**Comment by topherbuckley** [comment]
I know you only made changed to HelloIOIO, but going through the other modules:

- HelloIOIO: No issues
- HelloIOIOService: Doesn't stop when you click "stop" from the dropdown menu, but otherwise don't see any obvious issues. 
- HolidayIOIO: Failed to find camera. There is another nullpointer error. 
- IOIOConnectionTesterAndroid: No obvious issue, though don't have any actual tests for this other than loading the app. 
- IOIOManager: No obvious issue, though don't have any actual tests for this other than loading the app. 
- IOIOSimpleApp: No obvious issue, though don't have any actual tests for this other than loading the app. 
- IOIOTestBed: No intent perhaps? Doesn't show up with plugged into the phone. 
- IOIOTortureTest: No obvious issue, though don't have any actual tests for this other than loading the app. 
- ShoeBot: No obvious issue, though don't have any actual tests for this other than loading the app.

**Comment by topherbuckley** [comment]
I see you increased my privileged to contributor at some point. Thanks btw. How would you like me to continue with commits from this point? Would you still like me to use pull requests from my fork or make commits directly to here?

**Comment by hannesa2** [comment]
I prefer pull request to let CI build in advance. What's missing currently, is to smoke test with espresso

**Comment by topherbuckley** [comment]
Could you clarify if you mean pull requests from my fork, or if it is ok for me to create new branches with commits here (ytai/ioio) and create pull requests from these ytai/ioio branches? I can avoid committing directly to any branch you have created or are working on. I don't want to step on your toes, but rebasing my fork and associated branches all the time is getting a bit cumbersome now that I am actively trying to contribute. Although it would be my preference to manage separate branches here for things I'm working on, I'm happy to adapt either way, so please let me know your preference.

**Comment by hannesa2** [comment]
Creating branches direct here comes with the advantage to test your stuff easy. But when I add your fork as a remote has the same advantage.
What I want to prevent to have a lot of "dead" branches.
Outcome: it's up to you, where to create branches

**Comment by topherbuckley** [comment]
Understood. I'll do my best to delete any merged branches I create minimize any long-lived branches.

**Comment by hannesa2** [comment]
> Built successfully. Tested on Nexus 5 and crashed due to AppCompat theme missing in manifests. Updated this and works with a IOIOBoard to light the yellow LED. Will update all manifests to include this.

Great, thank you for your local test session ! This is very helpful

I'll merge this, then https://github.com/topherbuckley/ioio/pull/3 is much easier. No flavor handling is nor more needed concerning inject theme

**Comment by hannesa2** [comment]
Later, we could remove flavors, when jitpack.io is established

**Pull request merged**
