### PR TITLE
Inject theme based on build falvor.

### PR DESCRIPTION
**Pull request by topherbuckley**
Added one commit on top of ytai/theme, rebased to master, and now this PR from topherbuckley/theme. 

See #183.

Be sure to force remove ytai/theme branch after merging this.

### CODE REVIEW

**Comment by topherbuckley** [comment]
I guess I should also apply the same code to the remaining Android apps? Would you like that done before merging? Or did you just want this kind of functionality for a single test-app type scenario for some reason?

**Comment by hannesa2** [comment]
This complete topic #167 is a mess !
* Current master crash because of this 👎 
* During pull request of #167 it was not detected, because old library was used instead of current code 👎 
* I added two flavors to be able to use (current old) library or recent code. But to be honest there is no need to use library at all. But it's usefull to test future jitpack.io, so the flavors have only temporary character
* Now this PR is closed to fix the crash

The open question is: Do we need it for all sample apps ?
* Revert #167 and make topic again, but working ?
* Merge this PR ?
* All projects with #167 `AppCompatActivity` ?

**Comment by topherbuckley** [comment]
Let me start by apologizing for the mess. 

>Current master crash because of this

I'm not sure what you mean. You mean you cannot build from the current master? What is "crashing" and how? I can checkout the current master (df1a80a) and build successfully. I can also checkout the current tip of topherbuckley:theme (98c42f3) and build successfully. What is crashing on your end? 

>I added two flavors to be able to use (current old) library or recent code. But to be honest there is no need to use library at all. But it's usefull to test future jitpack.io, so the flavors have only temporary character

Although I like the idea of backwards compatibility by doing this, I also don't think it is very necessary as I don't think there is a huge user base that would be using the 5.08+ libraries we build as of yet. I think we can move forward with total AppCompatActivity inheritance and wait to see if anyone complains and needs Activity inheritance for some reason. I can then go back and implement all this flavor workaround stuff and provide two versions of the library if it looks like it this is really necessary. Until that point it seems like a lot of work for little benefit. 

How do the old library dependencies help test jitpack builds?  

>Revert #167 and make topic again, but working ?

I'm fine with this. If you revert, I can include those changes in the new theme branch to have everything regarding Activity->AppCompatActivity in one place and tested before merging to master again.

>Merge this PR ?

Not yet. I will continue to make a the necessary updates to theme before we merge ensuring a successful build. 

>All projects with #167 AppCompatActivity ?

All projects? You mean the sample apps? Or all classes (AbstractIOIOActivity, IOIOConnectionTesterActivity, DownloadUrlAcitivty). As the IOIOActivity currently inherits from AppCompatActivity, several, not just HelloIOIO are based on it already. 

I will try replacing all instances of Activity and see if it still builds. Have you worked on any unit or UI tests yet? I can test on my hardware again here if not.

**Comment by hannesa2** [comment]
Don't worry, shit happens 😄 

> How do the old library dependencies help test jitpack builds?

It's the base for #174 

> All projects? You mean the sample apps? Or all classes (AbstractIOIOActivity, IOIOConnectionTesterActivity, DownloadUrlAcitivty). As the IOIOActivity currently inherits from AppCompatActivity, several, not just HelloIOIO are based on it already.

I've no strong opinion here

> I'm fine with this. If you revert, I can include those changes in the new theme branch

Yes, currently, I've the feeling this is the right way, instead of fixing and fixing ...

I spent days (ok, every day just a one/two hours) to provide CI Espresso tests https://github.com/hannesa2/ioio/pull/4 But I'm fighting with the project structure. This was the main reason for #185 
image
Even `working-directory: ./software` doesn't work with `uses:`
The tests simply not start 👎 

The plan was to have proper tests before #167 is done new

**Comment by topherbuckley** [comment]
>It's the base for https://github.com/ytai/ioio/pull/174/files

If I update everything from Activity to AppCompatActivity, then nothing should depend on the old libraries. Then we can build on jitpack per normal right? 

>I spent days (ok, every day just a one/two hours) to provide CI Espresso tests hannesa2#4 But I'm fighting with the project structure. This was the main reason for #185
image
Even working-directory: ./software doesn't work with uses:
The tests simply not start -1

I'm very new to both github actions and espresso, but can try to help if you'd like. You want to make this branch a part of ytai or would you like me to PR to yours? 

>The plan was to have proper tests before #167 is done new

We can wait to merge topherbuckley:theme until after these tests are done if you'd like. Or I can just test on my local hardware as an initial testing point as well.

**Comment by topherbuckley** [comment]
Here how the PR looks on [my fork](https://github.com/topherbuckley/ioio/pull/3). No build or test failures and I tried out HelloIOIO on my hardware without issue. You want to recreate the ytai/theme branch or have me hold on to it in topherbuckley/theme until the esperession and/or unit tests are done?

**Comment by hannesa2** [comment]
> If I update everything from Activity to AppCompatActivity, then nothing should depend on the old libraries. Then we can build on jitpack per normal right?

I already remove the dependency of old library with #174 

> I'm very new to both github actions and espresso, but can try to help if you'd like. You want to make this branch a part of ytai or would you like me to PR to yours?
> 
> > The plan was to have proper tests before #167 is done new

It's done with #189 

> We can wait to merge topherbuckley:theme until after these tests are done if you'd like. Or I can just test on my local hardware as an initial testing point as well.

We can cherry-pick all necessary changes to a new branch

**Comment by topherbuckley** [comment]
Alright. I'll work on the new branch tomorrow and work in the reverted changes from before as well.

**Pull request closed without merging**
