### PR TITLE
Release on GitHub

### PR DESCRIPTION
**Pull request by hannesa2**
This will upload libaries artifacts to github release like 
https://github.com/hannesa2/ioio/releases/tag/6.0.0-beta4.r20

### CODE REVIEW

**Comment by hannesa2** [comment]
Now I wait for secret `GITHUBTOKEN` like this 

image

**Comment by topherbuckley** [comment]
Is there a reason this is not handled by [jitpack](https://jitpack.io/docs/ANDROID/#jar-file)? Seems like duplicate generation of aar files no?

**Comment by hannesa2** [comment]
> Is there a reason this is not handled by [jitpack](https://jitpack.io/docs/ANDROID/#jar-file)? Seems like duplicate generation of aar files no?

Jitpack has currently only Android aar , for PC the *.jar files are now on github, it's a kind of replace of directory `releases` and move stuff to github https://github.com/ytai/ioio/releases with artifacts

**Comment by topherbuckley** [comment]
> Jitpack has currently only Android aar  

Is that true? The doc link I sent seems to indicate you can also generate JAR files and points to [this file](https://github.com/jitpack/android-example/blob/master/library/build.gradle) as an example. 

It'd be nice if they were all in the same place if possible, but I agree that github releases make more sense than a releases folder.

**Comment by hannesa2** [comment]
> > Jitpack has currently only Android aar
> 
> Is that true? The doc link I sent seems to indicate you can also generate JAR files and points to [this file](https://github.com/jitpack/android-example/blob/master/library/build.gradle) as an example.
> 
> It'd be nice if they were all in the same place if possible, but I agree that github releases make more sense than a releases folder.

Now https://jitpack.io/#ytai/ioio/6.0.0.beta6 has `*.jar` as well 

image

**Comment by topherbuckley** [comment]
Nice job!

One issue I see with these still though is there doesn't appear to be any release notes, or anything to differentiate between releases. 

Is there a way to add release notes to these detailing what has been updated? It would likely take a bit more work to write these nicely for all beta releases, but at the very least, could we maybe just bundle all the master branch commit messages between the release and the previous release? For example I don't know if the newer releases are based on the AppCompat libraries or not without downloading the whole set and testing whether it breaks my project or not.

**Comment by topherbuckley** [comment]
Never mind. I had no idea github could do a diff on them [directly](https://github.com/ytai/ioio/compare/6.0.0.beta8...6.0.0-beta4). Not need for release notes if that is the case.

**Pull request merged**
