### PR TITLE
Inject theme based on build falvor.

### PR DESCRIPTION
**Pull request by topherbuckley**
This resolves the appcompat issues and allows a variable inheritance of IOIOActivity based on appCompat or not.

### CODE REVIEW

**Comment by topherbuckley** [comment]
I tried pushing the new commit directly to the ytai/theme branch, but it looks like I do not have write permissions despite the collaborator tag. I can continue working from my fork, but this adds a few extra steps to merging any pull requests like this (i.e. the tests show no failed checks, but this is only relative to the theme branch not to master no?). If you'd like me to push directly to a relevant branch in ytai, please provide the appropriate permissions.

**Comment by hannesa2** [comment]
Please rebase to recent master, it misses the flavor rename commit a69d259145

**Comment by topherbuckley** [comment]
I will go ahead and do that, but I guess this still feels like a clunky way of working on this, or I'm not understanding the benefits of the current way of doing things. If I originally rebased on master, and didn't make this pull request then the ytai/theme branch would become useless without any warning of it becoming so. I could add a comment that my pull request is a rebased version of ytai/theme and that you should force delete the ytai/theme branch after merging my PR, but this message, either by me forgetting to write it, or you forgetting to delete the branch, could be quite easily overlooked. 

You'd also see warnings on your end when trying to delete ytai/theme as it would claim not all changes have been merged. You could force delete it, but then I'd have to prune it locally here. After all that, we'd still have to make a pull request from my rebased topherbuckley/theme branch to ytai/master. 

Does it not make sense for me have write access to the theme branch, make a commit there, then make a pull request from there to ytai/master? This would eliminate all the above mentioned steps other than the final single pull request. Am I misunderstanding something?  Or is there a better way for me to work off your existing branches?

**Comment by hannesa2** [comment]
What are you doing ?

There was no need for a new PR.
A rebase would be this
```
git fetch upstream
git rebase upstream/master
git push -f
```

**Comment by topherbuckley** [comment]
Sorry, it appears I did something that would fit my typical single-person workflow, but does not work well under a shared workflow like this. 

I did rebase the same as you mentioned, but did not push this rebased branch directly as I found this convoluted the tree quite a bit due to ytai/theme being well behind ytai/master atm, and since a ff merge was not possible. So I made a new PR with an up to date theme branch. This made the tree a lot more legible, but I realize now that this was unnecessary and comes at the cost of creating all the confusion I talked about in my previous post. Also this way changes the intention from keeping the ytai/theme branch separate from ytai/master until further changes are made. Although there was some minor valid reasoning to what I was trying to do, overall, and in retrospect, I realize my decision was not justified.  

I am still relatively new to working on multi-person git projects, so I appreciate your patience. 

I can attempt to go back in my reflog to the point before I deleted the previous topherbuckley/theme branch, push this back to my fork and try to repoen this PR that way. Would that be your preferred route of resolution or how else would you like to proceed?

**Comment by topherbuckley** [comment]
I attempted to resolve this, but still didn't work quite as smoothly as I expected, so I'll leave it as is until you say otherwise. I had a look at what a new PR ytai/theme <-- topherbuckley/theme would look like, and it indeed looks a bit messy, so I won't open that until you say otherwise. Here is a screenshot of what it would potentially entail:

image

Is this what you were expecting?

**Comment by hannesa2** [comment]
I already remove the dependency of old library with #174
To test/develop this theme topic, you need a library with new theme changes, please use `def ioioVersion = "6.0.0-beta4"` for this.

`6.0.0-beta5` still uses `Activity` 
`6.0.0-beta4` uses `AppCompatActivity`

**Pull request closed without merging**
