### PR TITLE
Change project structure

### PR DESCRIPTION
**Pull request by hannesa2**
It's about to open project with any Intellij IDE (Android Studio) and see complete project.
Additionally, CI yaml files can be edited in Android Studio now

### CODE REVIEW

**Comment by hannesa2** [comment]
The content of directory `software` is moved one level up and directory `software` is deleted now

**Comment by hannesa2** [comment]
I deleted old apk files in repo

**Comment by topherbuckley** [comment]
I'd be against this for [these](https://github.com/ytai/ioio/commit/af08e734e2a7693c61c394ef17fd571550b41b75#commitcomment-42003878) reasons.

**Comment by hannesa2** [comment]
Ok, keep old structure with current issues

**Comment by topherbuckley** [comment]
I just point my Android Studio to software rather than the root dir. Yes, this means the yaml files won't show up, but if this is a big issue, I'll try to search for some way to point to them (do links work in a git repo?).

**Comment by hannesa2** [comment]
Yes this is one issue, but CI has more issues with it eg changing directories
Additionally the repo is more or less a gradle repo, but it's not made to open root with a Intellij IDE (Android Studio)

**Comment by topherbuckley** [comment]
See #186. This seems to solve one issue at least.

**Comment by topherbuckley** [comment]
>CI has more issues with it eg changing directories

Is this not solved by the working-directory keyword I mentioned [here](https://github.com/ytai/ioio/commit/af08e734e2a7693c61c394ef17fd571550b41b75#commitcomment-42001978)

>Additionally the repo is more or less a gradle repo, but it's not made to open root with a Intellij IDE (Android Studio)

I'm not sure I understand the logic there. Does gradle do anything to any file other than those in software? (I haven't touched anything other than that so far, so maybe it does build other things).  Does Android Studio actually do anything useful for the other contents of the repo other than what is in software?

Also, this is how I structure my own project as well (as it is also a mix of hardware/software and others). I tried a while ago to separate each discipline into separate repos but it was a pain in the ass to keep things unified, and later gave up on the idea.

**Comment by hannesa2** [comment]
I reopen to continue for discussion

**Comment by hannesa2** [comment]
Sorry, I'm not able to reopen this 

image

That's why I create a new one #190

**Comment by oracle3987** [comment]
Why did this happen with out my knowledge

**Pull request closed without merging**
